### ISSUE TITLE
Database for staging1 and live

### ISSUE THREAD

**Issue by AlexInntekt** [AlexInntekt/arta-restaurarii#1]
create database for staging1 and live

**Comment by ionescu77** [comment]
Păi boss:
1. dă și assign când faci issue ca să am și eu notificare ceva
2. Are you serious? Ăsta e tichet? Scrie și tu clar ce vrei, altfel o să îți urez să primești numai astfel de tichete la viața ta :)

- numele bazei de date
- user-ul

Niste detalii, sau poate o fi în trecută deja în tabelul google cu environments, că nu m-am uitat și tichetul nu-mi spune.

Hai please, profi work tichet, profi results.

**Comment by AlexInntekt** [comment]
Doua baze de date necesare:

Pentru productie:
    -Name:  arta-live
    -User:    arta-live-user
    
Staging:
    -Name:   arta-staging
    -User:     arta-staging-user

Comunicati-mi parola dupa creare. Multumesc

**Comment by ionescu77** [comment]
Will proceed now.

I was also expecting to see the 2 environments added here already:

https://docs.google.com/spreadsheets/d/12dNShmnzQ3TMhuisi3rO3Z22DsocarnzA2hxsglOqno/edit#gid=0

**Comment by ionescu77** [comment]
Am creat:

- parolele le trimit prin mesaj
- din pacate nu pot folosi `-` in nume, doar lowercase
- dupa o privire in google sheet am adoptat o formatare mai standard.

```postgresql
[razvansky@spaceport myScripts]$ sudo su - postgres
Last login: Wed Apr 10 18:35:55 EEST 2019 on pts/0
-bash-4.2$ psql
psql (10.8)
Type "help" for help.

postgres=# CREATE DATABASE arta-live-db;
ERROR:  syntax error at or near "-"
LINE 1: CREATE DATABASE arta-live-db;
                            ^
postgres=# CREATE DATABASE artalivedb;
CREATE DATABASE
postgres=# CREATE DATABASE artastagingdb;
CREATE DATABASE
postgres=# CREATE USER artalivedb_user WITH PASSWORD '--hidden--';
CREATE ROLE
postgres=# CREATE USER artastagingdb_user WITH PASSWORD '--hidden--';
CREATE ROLE
postgres=# ALTER ROLE artalivedb_user SET client_encoding TO 'utf8';
ALTER ROLE
postgres=# ALTER ROLE artastagingdb_user SET client_encoding TO 'utf8';
ALTER ROLE
postgres=# ALTER ROLE artalivedb_user SET default_transaction_isolation TO 'read committed';
ALTER ROLE
postgres=# ALTER ROLE artastagingdb_user SET default_transaction_isolation TO 'read committed';
ALTER ROLE
postgres=# ALTER ROLE artalivedb_user SET timezone TO 'UTC';
ALTER ROLE
postgres=# ALTER ROLE artastagingdb_user SET timezone TO 'UTC';
ALTER ROLE
postgres=# GRANT ALL PRIVILEGES ON DATABASE artalivedb TO artalivedb_user;
GRANT
postgres=# GRANT ALL PRIVILEGES ON DATABASE artastagingdb TO artastagingdb_user;
GRANT
postgres=#
```

**Comment by ionescu77** [comment]
Assigning to Alex. He can close it if he is happy!

**Comment by AlexInntekt** [comment]
For staging, what works:      

```
  'NAME': 'artastagingdb',
   'USER': 'artastagingdb_user',
```

Password received through another channel. 
Thank you @ionescu77 , I will let you know the progress.
