### ISSUE TITLE
Add environment data for arta-restaurarii to Google Sheets Environments

### ISSUE THREAD

**Issue by ionescu77** [AlexInntekt/arta-restaurarii#2]
@AlexInntekt 

Please add environment data for arta-restaurarii to Google Sheets Environments

https://docs.google.com/spreadsheets/d/12dNShmnzQ3TMhuisi3rO3Z22DsocarnzA2hxsglOqno/edit#gid=0

**Comment by ionescu77** [comment]
any updates? can we close it?

**Comment by AlexInntekt** [comment]
I did add the environments in the Google Sheets 
I am closing it. thank you
